In [59]:
import numpy as np

In [60]:
b = np.array([[1,2, 3],[3, 4, 5]])
a = np.array([[1, 2, 4, 5, 6, 8],[5, 6, 7, 8, 9, 2],[12, 2, 23, 2, 22, 2]])

print(b)

[[1 2 3]
 [3 4 5]]


In [61]:
type(b)

numpy.ndarray

In [62]:
print(b.size)
print(a.size)


6
18


In [63]:
print(b.shape)
print(a.shape)

(2, 3)
(3, 6)


In [64]:
print(b.dtype)
print(a.dtype)

int32
int32


In [65]:
d = np.array([[1, 2, 3, 4, 4.5, 5, 7],[4, 5, 6, 7, 8, 9, 6],[9, 8, 8, 7.5, 76, 6, 6]])
print(d)
print(d.dtype)

[[ 1.   2.   3.   4.   4.5  5.   7. ]
 [ 4.   5.   6.   7.   8.   9.   6. ]
 [ 9.   8.   8.   7.5 76.   6.   6. ]]
float64


In [66]:

print(d.transpose)
print(d)

<built-in method transpose of numpy.ndarray object at 0x00000261AE9CE0D0>
[[ 1.   2.   3.   4.   4.5  5.   7. ]
 [ 4.   5.   6.   7.   8.   9.   6. ]
 [ 9.   8.   8.   7.5 76.   6.   6. ]]


np.empty((rows,cols), dtype)

In [67]:
np.empty((4,4), dtype= int)

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 7077980, 7209061],
       [7733359, 6029423, 7340097, 4456560],
       [7602273, 6029409, 7274572, 6357091]])

np.one ((rows, cols ),dtype)

In [68]:
x = np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [69]:
y = np.ones((3,4), dtype= int)
y

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [70]:
z = np.ones((3,5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

np.zero((rows, cols),dtype)

In [71]:
a = np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [72]:
B = np.zeros((3,5))
B


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
c = np.zeros((3,5),dtype=str)
c

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [74]:
E = np.ones((2,3),dtype=str)
E

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [75]:
F = np.zeros((4,5),dtype=bool)
F

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [76]:
G = np.ones((2,4),dtype=bool)
G

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

np.arange(start,end,step)

In [77]:
x = np.arange(1,20)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [78]:
x = np.arange(2,30,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [79]:
x = np.arange(1,20,2)
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [80]:
x = np.arange(2,20,2)
print(x)

[ 2  4  6  8 10 12 14 16 18]


arr.reshape((rows, col))

In [81]:
x = x.reshape(3,3)
print(x)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [82]:
B = np.arange(1,100,2)
print(B)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [83]:
B = B.reshape(10,5)
print(B)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


In [84]:
B = B.flatten()
B

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [85]:
B = B.ravel()
B

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

a.revel() : (i) Return only refence / view of original array. (ii) if you modify the array you would notice that the value of the value of original arrray also change . (iii) revel is faster then fltten() as it does not occupy any memory . (iv) revel is a library-level finction .

a.flatten 9 : (i) Return copy of the original array (ii) if you modify the arrsy value of originl array is not affected. (iii) flatten() is comparatively slower the revel() as it  occupies memory. (iv) fletten is method of an ndarray object.

In [86]:
a = np.arange(1,51)
a = a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [87]:
a[0]

array([1, 2, 3, 4, 5])

In [88]:
a[2]

array([11, 12, 13, 14, 15])

In [89]:
a[0,0]

1

In [90]:
a[3,4]

20

In [91]:
a[1:4]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [92]:
a[0:10]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [93]:
a[:,2]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [94]:
a[2: 5,4]

array([15, 20, 25])

In [95]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [96]:
a[:,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [97]:
a[:,2:5].dtype

dtype('int32')

In [98]:
a = np.arange(1,51)
a = a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [99]:
a = np.arange(0, 18).reshape((6,3))
b = np.arange(20, 38).reshape((6,3))
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [100]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [101]:
b-a

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [102]:
a-b

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [103]:
np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [104]:
a*b

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [105]:
np.multiply(a,b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [106]:
a/b

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [107]:
np.divide(a,b)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [108]:
print(a.shape)
print(b.shape)

(6, 3)
(6, 3)


In [109]:
b  = b.reshape(3,6)

In [110]:
a@b

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [111]:
a.dot(b)

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [112]:
b.max()

37

In [113]:
b.min()

20

In [114]:
b.argmax()

17

In [115]:
np.sum(b)

513

In [116]:
np.sum (b, axis=1)

array([135, 171, 207])

In [117]:
np.sum(b, axis= 0)

array([78, 81, 84, 87, 90, 93])

In [118]:
np.mean(b)

28.5

In [119]:
np.median(b)

28.5

In [120]:
np.square(b)

array([[ 400,  441,  484,  529,  576,  625],
       [ 676,  729,  784,  841,  900,  961],
       [1024, 1089, 1156, 1225, 1296, 1369]])

In [121]:
np.sqrt(b)

array([[4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
        5.56776436],
       [5.65685425, 5.74456265, 5.83095189, 5.91607978, 6.        ,
        6.08276253]])

In [122]:
np.std(b)

5.188127472091127

In [123]:
np.log(b)

array([[2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582],
       [3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
        3.4339872 ],
       [3.4657359 , 3.49650756, 3.52636052, 3.55534806, 3.58351894,
        3.61091791]])