In [70]:
import numpy as np

In [71]:
np.random.random(1)

array([0.25450047])

In [72]:
np.random.random(2)


array([0.52666108, 0.35900985])

In [73]:
np.random.random((2,2))


array([[0.17340912, 0.83452328],
       [0.77625476, 0.26248861]])

In [89]:
np.random.randint(1,10)

1

In [96]:
np.random.randint(1,10, (2,2))

array([[6, 9],
       [7, 6]])